name: Publish package to pub.dev
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter pub run tool/publish/check_version.dart ${GITHUB_REF}
      - name: Analyze
        run: flutter analyze
      - name: Format
        run: dart format --set-exit-if-changed .
  publish:
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
